import java.sql.Connection;
import java.sql.DriverManager; 
import java.sql.SQLException; 
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class NewJFrame extends javax.swing.JFrame {
        Connection con;
        Statement stmt;
        ResultSet rs;
        int corRow = 0;
        
    public NewJFrame() {
        initComponents();
        setResizable(false);
        DoConnect();
        btn_SNR.setEnabled(false);
        btn_UR.setEnabled(false);
        btn_CNR.setEnabled(false);
        tf_id.setEditable(false);
        tf_FN.setEditable(false);
        tf_LN.setEditable(false);
        TF_course.setEditable(false);
    }
    
    public void DoConnect (){
        try
        {
        String host = "jdbc:derby://localhost:1527/student";
        String uName = "admin1";
        String uPass = "admin1";
        con = DriverManager.getConnection(host, uName, uPass);
        stmt = con.createStatement (ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE );
        String SQL = "select * from students";
        rs = stmt.executeQuery(SQL);

        rs.next();
        int id_col = rs.getInt("id");
        String id = Integer.toString(id_col);
        String f_name = rs.getString("first_name");
        String l_name = rs.getString("last_name"); 
        String courses = rs.getString("Course");
    
        tf_id.setText(id);
        tf_FN.setText (f_name);
        tf_LN.setText (l_name);
        TF_course.setText(courses);
        }
        catch(SQLException er){
            JOptionPane.showMessageDialog(this, er.getMessage());
        }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_FN = new javax.swing.JTextField();
        tf_LN = new javax.swing.JTextField();
        TF_course = new javax.swing.JTextField();
        btn_UR = new javax.swing.JButton();
        btn_DR = new javax.swing.JButton();
        btn_NR = new javax.swing.JButton();
        btn_SNR = new javax.swing.JButton();
        btn_CNR = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_prev = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        btn_E = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        jLabel1.setText("Student ID");

        jLabel2.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        jLabel3.setText("Last Name");

        jlabel.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        jlabel.setText("Course");

        tf_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });

        tf_FN.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_FN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_FNActionPerformed(evt);
            }
        });

        tf_LN.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tf_LN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_LNActionPerformed(evt);
            }
        });

        TF_course.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TF_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_courseActionPerformed(evt);
            }
        });

        btn_UR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_UR.setText("Update Record");
        btn_UR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_URActionPerformed(evt);
            }
        });

        btn_DR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_DR.setText("Delete Record");
        btn_DR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DRActionPerformed(evt);
            }
        });

        btn_NR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_NR.setText("New Record");
        btn_NR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NRActionPerformed(evt);
            }
        });

        btn_SNR.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        btn_SNR.setText("Save New Record");
        btn_SNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SNRActionPerformed(evt);
            }
        });

        btn_CNR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_CNR.setText("Cancel");
        btn_CNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CNRActionPerformed(evt);
            }
        });

        btn_first.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_first.setText("FIRST");
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        btn_next.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_next.setText("NEXT");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_prev.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_prev.setText("PREV");
        btn_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prevActionPerformed(evt);
            }
        });

        btn_last.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_last.setText("LAST");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        btn_E.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_E.setText("Edit Record");
        btn_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EActionPerformed(evt);
            }
        });

        btn_logout.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_CNR, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(btn_UR, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tf_FN, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btn_first, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_prev, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel3)
                                .addGap(57, 57, 57)
                                .addComponent(tf_LN, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jlabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TF_course, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_last, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_next, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(143, 143, 143)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_E, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_SNR, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NR, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DR, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_LN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_E, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel)
                    .addComponent(tf_FN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TF_course, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_DR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_next, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_prev, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_NR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SNR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_last, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_first, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CNR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_UR, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    private void tf_FNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_FNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_FNActionPerformed

    private void tf_LNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_LNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_LNActionPerformed

    private void TF_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_courseActionPerformed

    private void btn_URActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_URActionPerformed
           try {
        // Get the data from the input fields
        String id = tf_id.getText();
        String firstName = tf_FN.getText();
        String lastName = tf_LN.getText();
        String course = TF_course.getText();
        
        btn_first.setEnabled(true);
        btn_prev.setEnabled(true);
        btn_last.setEnabled(true);
        btn_next.setEnabled(true);
        btn_UR.setEnabled(true);
        btn_DR.setEnabled(true);
        btn_NR.setEnabled(true);
        btn_SNR.setEnabled(false);
        btn_CNR.setEnabled(false);
            
        tf_id.setEditable(false);
        tf_FN.setEditable(false);
        tf_LN.setEditable(false);
        TF_course.setEditable(false);

        // Update the current row with the new data
        rs.updateString("id", id);
        rs.updateString("first_name", firstName);
        rs.updateString("last_name", lastName);
        rs.updateString("course", course);
        
        //commit the changes para shessh
        rs.updateRow();

        JOptionPane.showMessageDialog(NewJFrame.this, "Record updated");
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(NewJFrame.this, ex.getMessage());
    }
    }//GEN-LAST:event_btn_URActionPerformed

    private void btn_DRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DRActionPerformed
    try {
        int confirm = JOptionPane.showConfirmDialog(NewJFrame.this,
                "Are you sure you want to delete this record?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            rs.deleteRow();
            JOptionPane.showMessageDialog(NewJFrame.this, "Record deleted");
            String SQL = "select * from students";
            rs = stmt.executeQuery(SQL);
            
            //clear textfields
            tf_id.setText("");
            tf_FN.setText("");
            tf_LN.setText("");
            TF_course.setText("");
            
            //make them non-editable gumawa na ako function
            disableEditing();
        } 
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(NewJFrame.this, ex.getMessage());
    }
    }//GEN-LAST:event_btn_DRActionPerformed

    private void btn_NRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NRActionPerformed
        btn_first.setEnabled(false);
        btn_prev.setEnabled(false);
        btn_last.setEnabled(false);
        btn_next.setEnabled(false);
        btn_UR.setEnabled(false);
        btn_DR.setEnabled(false);
        btn_NR.setEnabled(false);
        btn_E.setEnabled(false);
        
        btn_SNR.setEnabled(true);
        tf_id.setEditable(true);
        tf_FN.setEditable(true);
        tf_LN.setEditable(true);
        TF_course.setEditable(true);
        btn_SNR.setEnabled(true);
        btn_CNR.setEnabled(true);
        
        tf_id.setText("");
        tf_FN.setText("");
        tf_LN.setText("");
        TF_course.setText("");
        
        try{
            int curRow = rs.getRow();
        }   catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btn_NRActionPerformed

    private void btn_SNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SNRActionPerformed
        // TODO add your handling code here:
        try {
            // Move cursor to the new row
            rs.moveToInsertRow();
            
            // Get the data from the input fields
            String id = tf_id.getText();
            String firstName = tf_FN.getText();
            String lastName = tf_LN.getText();
            String course = TF_course.getText();

            // Set the values to the new row
            rs.updateString("id", id);
            rs.updateString("first_name", firstName);
            rs.updateString("last_name", lastName);
            rs.updateString("course", course);

            // Insert the new row
            rs.insertRow();
            
            JOptionPane.showMessageDialog(NewJFrame.this, "New record is saved");
            
            
            String SQL = "select * from students";
            rs = stmt.executeQuery(SQL);
            // Re-enable buttons
            btn_first.setEnabled(true);
            btn_prev.setEnabled(true);
            btn_last.setEnabled(true);
            btn_next.setEnabled(true);
            btn_UR.setEnabled(true);
            btn_DR.setEnabled(true);
            btn_NR.setEnabled(true);
            btn_SNR.setEnabled(false);
            btn_CNR.setEnabled(false);
            
            tf_id.setEditable(false);
            tf_FN.setEditable(false);
            tf_LN.setEditable(false);
            TF_course.setEditable(false);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(NewJFrame.this, ex.getMessage());
        }
    }//GEN-LAST:event_btn_SNRActionPerformed

    private void btn_CNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CNRActionPerformed
        // TODO add your handling code here:
        try{
            int curRow = rs.getRow();
            rs.absolute(curRow);
            tf_FN.setText(rs.getString("first_name"));
            tf_LN.setText(rs.getString("last_name"));
            TF_course.setText(rs.getString("Course"));
            tf_id.setText(rs.getString("id"));
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
        }
        
            btn_first.setEnabled(true);
            btn_prev.setEnabled(true);
            btn_last.setEnabled(true);
            btn_next.setEnabled(true);
            btn_UR.setEnabled(false);
            btn_DR.setEnabled(true);
            btn_NR.setEnabled(true);
             btn_E.setEnabled(true);
            btn_SNR.setEnabled(false);
            btn_CNR.setEnabled(false);
    }//GEN-LAST:event_btn_CNRActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        try{
            if(rs.next()){
                int id_col = rs.getInt("ID");
                String id = Integer.toString(id_col);
                String first = rs.getString("First_Name");
                String last = rs.getString("Last_Name");
                String course = rs.getString("Course");
                
                tf_id.setText(id);
                tf_FN.setText(first);
                tf_LN.setText(last);
                TF_course.setText(course);
            }
            else{
                rs.next();
                JOptionPane.showMessageDialog(NewJFrame.this, "End of Database");
            }
        }   catch (SQLException ex) {
                Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        // TODO add your handling code here:
        try{
            rs.first();
                int id_col = rs.getInt("ID");
                String id = Integer.toString(id_col);
                String first = rs.getString("First_Name");
                String last = rs.getString("Last_Name");
                String course = rs.getString("Course");
                
                tf_id.setText(id);
                tf_FN.setText(first);
                tf_LN.setText(last);
                TF_course.setText(course);
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prevActionPerformed

        try{
            if(rs.previous()) {
                int id_col = rs.getInt("ID");
                String id = Integer.toString(id_col);
                String first = rs.getString("First_Name");
                String last = rs.getString("Last_Name");
                String course = rs.getString("Course");
                
                tf_id.setText(id);
                tf_FN.setText(first);
                tf_LN.setText(last);
                TF_course.setText(course);
            }
            else {
                rs.next();
                JOptionPane.showMessageDialog(NewJFrame.this, "Start of Database");
            }
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
    }//GEN-LAST:event_btn_prevActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        // TODO add your handling code here:
        try{
            rs.last();
                int id_col = rs.getInt("ID");
                String id = Integer.toString(id_col);
                String first = rs.getString("First_Name");
                String last = rs.getString("Last_Name");
                String course = rs.getString("Course");
                
                tf_id.setText(id);
                tf_FN.setText(first);
                tf_LN.setText(last);
                TF_course.setText(course);
        }
        catch (SQLException err){
            JOptionPane.showMessageDialog(NewJFrame.this, err.getMessage());
        }
    }//GEN-LAST:event_btn_lastActionPerformed

    private void btn_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EActionPerformed
        // TODO add your handling code here:
            tf_id.setEditable(true);
            tf_FN.setEditable(true);
            tf_LN.setEditable(true);
            TF_course.setEditable(true);
        
            btn_first.setEnabled(false);
            btn_prev.setEnabled(false);
            btn_last.setEnabled(false);
            btn_next.setEnabled(false);
            btn_UR.setEnabled(true);
            btn_DR.setEnabled(false);
            btn_NR.setEnabled(false);
            btn_SNR.setEnabled(false);
            btn_CNR.setEnabled(true);
    }//GEN-LAST:event_btn_EActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        // Show a confirmation dialog before logging out
    int confirmed = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to log out?", "Logout Confirmation",
            JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
        // Close the current form
        this.setVisible(false);
        this.dispose();
        
        // Open the login form
        new LoginForm().setVisible(true);
    }
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TF_course;
    private javax.swing.JButton btn_CNR;
    private javax.swing.JButton btn_DR;
    private javax.swing.JButton btn_E;
    private javax.swing.JButton btn_NR;
    private javax.swing.JButton btn_SNR;
    private javax.swing.JButton btn_UR;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_prev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlabel;
    private javax.swing.JTextField tf_FN;
    private javax.swing.JTextField tf_LN;
    private javax.swing.JTextField tf_id;
    // End of variables declaration//GEN-END:variables

    private void disableEditing() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
